name: Compile Arduino Mega sketch

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile headless configuration
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:mega
          platforms: |
            - name: arduino:avr
              version: 1.8.8
          libraries: '[]'
          sketch-paths: |
            - .
          enable-warnings-report: true

      - name: Compile keypad and LCD configuration
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:mega
          platforms: |
            - name: arduino:avr
              version: 1.8.8
          libraries: '[]'
          sketch-paths: |
            - .
          cli-compile-flags: |
            - --build-property
            - compiler.cpp.extra_flags=-DUI_KEYPAD_LCD
          enable-warnings-report: true

      - name: Compile SPI touchscreen configuration
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:mega
          platforms: |
            - name: arduino:avr
              version: 1.8.8
          libraries: |
            - name: Adafruit GFX Library
            - name: Adafruit ILI9341
            - name: XPT2046_Touchscreen
          sketch-paths: |
            - .
          cli-compile-flags: |
            - --build-property
            - compiler.cpp.extra_flags=-DUI_SPI_TOUCHSCREEN
          enable-warnings-report: true
